---
title: "ncaa_cross"
format: html
editor: visual
---

```{r Setup, include = FALSE}

# Load packages
library(janitor)  # cleaning
library(dplyr)  # cleaning
library(tidyr)  # cleaning
library(lubridate)  # cleaning dates and times
library(ggplot2)  # plotting
library(forcats)  # dealing with factors
library(stringr)  # wrapping text
library(showtext)  # fonts

```

```{r Load data and clean}

# Read raw data file
raw_data <- read.csv("data/team_champs.csv") %>% 
  clean_names()

# Update champion column to factor
team_champs <- raw_data %>% 
  mutate(champion = as.factor(champion)) %>% 
  group_by(champion) %>% 
  mutate(max_year = max(year)) %>% 
  arrange(year)
  
# Create data frame that counts how many total championships
team_champs_count<- team_champs %>% 
  group_by(champion) %>% 
  summarise(counts = n()) %>% 
  arrange(desc(counts))

```

```{r All Years Plot}

showtext_auto()

ncaa_cross_all_plot <- team_champs %>% 
  ggplot(
    mapping = aes(x = year, y = reorder(champion, max_year), 
                  label = substr(year, start = 3, stop = nchar(year)))) +
  theme_classic() +
  theme(
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white"),
    text = element_text(family = "Roboto"),
    plot.title.position = "plot",
    plot.caption.position = "plot",
    plot.title = element_text(size = 14, face = "bold", family = "Roboto Condensed", color = "#2A3F4D", margin = margin(b = 5)),
    plot.subtitle = element_text(size = 9, color = "#2A3F4D", margin = margin(b = 15)),
    plot.caption = element_text(size = 8, face = "italic", hjust = 0, margin = margin(t = 10)),
    panel.grid.major.y = element_line(color = "#2A3F4D", linewidth = 0.25, linetype = "dotted"),
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    axis.text.x = element_text(size = 9, color = "#2A3F4D", margin = margin(t = 2)),
    axis.text.y = element_text(size = 10, color = "#2A3F4D")
  ) +
  labs(
    title = "NCAA Cross Country Champions",
    subtitle = str_wrap("While NAU has been dominant recently, with double three-peats to win six out of the last eight years, the legendary Arkansas program is still the standard, winning 11 times over 17 years in the 80s and 90s.", 104),
    caption = "Data: ncaa.com\nViz: Tim Fulton, PhD",
    x = "Age"
  ) +
  geom_point(
    shape = 95,
    size = 7, 
    color = "#466A80"
  ) +
  geom_text(
    size = 2.6,
    color = "#466A80",
    nudge_y = 0.3,
    fontface = "bold",
    family = "Roboto"
  ) +
  scale_x_continuous(
    breaks = seq(1940, 2020, 10),
    expand = expansion(mult = 0.015)
  ) 


ggsave("plots/ncaa_cross_all.png",
  plot = ncaa_cross_all_plot,
  width = 13,
  height = 7,
  units = "in",
  dpi = 600
)


```


```{r modern era plot}

showtext.auto()

# Filter original data frame to 1965 and beyond and create enew column
team_champs_era <- team_champs %>% 
  filter(year >= 1965) %>% 
  mutate(era_champion = case_when(champion == "UTEP" ~ "UTEP",
                                  champion == "Arkansas" ~ "Arkansas",
                                  champion == "Northern Arizona" ~ "Northern Arizona",
                                  champion == "Oregon" ~ "Oregon",
                                  TRUE ~ "Other"))

team_champs_era$era_champion <- factor(team_champs_era$era_champion, levels = c("Other", "UTEP", "Arkansas", "Oregon", "Northern Arizona"))

# Plot
ncaa_cross_era_plot <- team_champs_era %>% 
  ggplot(
    mapping = aes(x = year, y = era_champion, 
                  label = substr(year, start = 3, stop = nchar(year)))) +
  theme_classic() +
  theme(
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white"),
    text = element_text(family = "Roboto"),
    plot.title.position = "plot",
    plot.caption.position = "plot",
    plot.title = element_text(size = 14, face = "bold", family = "Roboto Condensed", color = "#2A3F4D", margin = margin(b = 5)),
    plot.subtitle = element_text(size = 9, color = "#2A3F4D", margin = margin(b = 5)),
    plot.caption = element_text(size = 8, face = "italic", hjust = 0, margin = margin(t = 10)),
    panel.grid.major.y = element_line(color = "#2A3F4D", linewidth = 0.25, linetype = "dotted"),
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    axis.text.x = element_text(size = 9, color = "#2A3F4D", margin = margin(t = -10)),
    axis.text.y = element_text(size = 10, color = "#2A3F4D")
  ) +
  labs(
    title = "NCAA Cross Country Champions",
    subtitle = str_wrap("Four programs have more combined championships than all other programs in total. While NAU has been dominant recently, with double three-peats to win six out of the last eight years, the legendary Arkansas program is still the standard, winning 11 times over 17 years in the 80s and 90s.", 104),
    caption = "Data: ncaa.com\nViz: Tim Fulton, PhD",
    x = "Age"
  ) +
  geom_point(
    shape = 95,
    size = 6, 
    color = "#466A80"
  ) +
  geom_text(
    size = 2.6,
    color = "#466A80",
    nudge_y = 0.1,
    family = "Roboto"
  ) +
  scale_x_continuous(
    breaks = seq(1960, 2020, 10),
    expand = expansion(mult = 0.015)
  ) 


# Save plot
ggsave("plots/ncaa_cross_era.png",
  plot = ncaa_cross_era_plot,
  width = 10,
  height = 5,
  units = "in",
  dpi = 600
)


```
